"""
LoRA fine-tune Gemma 4 E2B on the bounds-gemma PHI corpus.

Designed to run on a Colab T4 (16 GB VRAM) with Unsloth's 4-bit
quantisation. Total runtime on T4 for 500 examples × 3 epochs is
roughly 25-45 minutes, plus 15-20 minutes for export to GGUF and
LiteRT-LM .task formats.

Inputs:
  - finetune/data/phi_training.jsonl (generated by generate_phi_dataset.mjs)

Outputs:
  - bounds-gemma-e2b-phi-ft/                      <- LoRA adapter weights
  - bounds-gemma-e2b-phi-ft/merged/               <- full model (LoRA merged into base)
  - bounds-gemma-e2b-phi-ft-gguf/                 <- Ollama-compatible GGUF
  - bounds-gemma-e2b-phi-ft.task                  <- LiteRT-LM .task for WebLLM/MediaPipe

Usage on Colab T4:

    !pip install unsloth datasets transformers trl
    !git clone https://github.com/Aqta-ai/bounds-gemma
    %cd bounds-gemma
    # Upload phi_training.jsonl to finetune/data/ via the Colab file panel,
    # OR pull from your storage if you've staged it elsewhere.
    !python finetune/scripts/train.py

Usage locally (Apple Silicon, MPS):

    pip install unsloth-no-deps datasets transformers trl mlx-lm
    python finetune/scripts/train.py

Honest scope: this trains the LoRA adapter and merges it back into the
base for export. It does NOT run a held-out evaluation against a
clinical corpus (we don't have one with a DUA cleared in time for the
submission). Quality validation falls to the smoke test in
examples/runOllama.ts after the GGUF is loaded into Ollama.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

BASE_MODEL = os.environ.get("BASE_MODEL", "unsloth/gemma-4-E2B-it-bnb-4bit")
TRAIN_DATA = Path(os.environ.get("TRAIN_DATA", "finetune/data/phi_training.jsonl"))
OUTPUT_DIR = Path(os.environ.get("OUTPUT_DIR", "bounds-gemma-e2b-phi-ft"))
MERGED_DIR = OUTPUT_DIR / "merged"

# LoRA configuration. r=16 is the default sweet spot for instruction
# fine-tuning on Unsloth; alpha=16 keeps the update magnitude balanced.
LORA_R = int(os.environ.get("LORA_R", "16"))
LORA_ALPHA = int(os.environ.get("LORA_ALPHA", "16"))
LORA_DROPOUT = float(os.environ.get("LORA_DROPOUT", "0.0"))
MAX_SEQ_LENGTH = int(os.environ.get("MAX_SEQ_LENGTH", "4096"))

# Training. 3 epochs is enough at this corpus size; more risks overfit
# given the synthetic-data caveat.
NUM_EPOCHS = int(os.environ.get("NUM_EPOCHS", "3"))
BATCH_SIZE = int(os.environ.get("BATCH_SIZE", "2"))
GRADIENT_ACCUMULATION = int(os.environ.get("GRADIENT_ACCUMULATION", "4"))
LEARNING_RATE = float(os.environ.get("LEARNING_RATE", "2e-4"))
WARMUP_STEPS = int(os.environ.get("WARMUP_STEPS", "5"))


def load_training_data():
    """Stream the JSONL into a HF Datasets object."""
    from datasets import Dataset

    if not TRAIN_DATA.exists():
        raise FileNotFoundError(
            f"Training data missing: {TRAIN_DATA}. "
            f"Run finetune/scripts/generate_phi_dataset.mjs first, or upload "
            f"phi_training.jsonl to finetune/data/ in this Colab session."
        )

    records = []
    with TRAIN_DATA.open("r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            records.append(json.loads(line))

    print(f"Loaded {len(records)} training examples from {TRAIN_DATA}")
    if len(records) < 50:
        print(
            f"WARNING: only {len(records)} examples. Expect 200+ for a "
            f"meaningful LoRA. Training will continue but the resulting "
            f"adapter may overfit."
        )
    return Dataset.from_list(records)


def main():
    print(f"Base model:      {BASE_MODEL}")
    print(f"Training data:   {TRAIN_DATA}")
    print(f"Output dir:      {OUTPUT_DIR}")
    print(f"LoRA r={LORA_R}, alpha={LORA_ALPHA}, dropout={LORA_DROPOUT}")
    print(f"Epochs={NUM_EPOCHS}, batch={BATCH_SIZE}, grad-accum={GRADIENT_ACCUMULATION}, lr={LEARNING_RATE}")
    print()

    # Lazy imports so the cells above can be run for config inspection
    # without paying the multi-second Unsloth import cost.
    from unsloth import FastLanguageModel
    from unsloth.chat_templates import get_chat_template
    from trl import SFTTrainer
    from transformers import TrainingArguments
    import torch

    # 1. Load base model in 4-bit
    print("[1/6] Loading base model (4-bit quantised)…")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=BASE_MODEL,
        max_seq_length=MAX_SEQ_LENGTH,
        dtype=None,  # Unsloth picks bf16/fp16 automatically
        load_in_4bit=True,
    )

    # Gemma uses the gemma chat template; Unsloth ships it ready
    tokenizer = get_chat_template(tokenizer, chat_template="gemma")

    # 2. Apply LoRA adapters
    print("[2/6] Attaching LoRA adapters…")
    model = FastLanguageModel.get_peft_model(
        model,
        r=LORA_R,
        target_modules=[
            "q_proj",
            "k_proj",
            "v_proj",
            "o_proj",
            "gate_proj",
            "up_proj",
            "down_proj",
        ],
        lora_alpha=LORA_ALPHA,
        lora_dropout=LORA_DROPOUT,
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=3407,
        use_rslora=False,
    )

    # 3. Load and format training data
    print("[3/6] Loading training data…")
    dataset = load_training_data()

    def format_example(ex):
        # Use the tokenizer's apply_chat_template to convert the
        # messages array into the model's expected prompt format.
        # Unsloth + Gemma expects {"text": "<formatted string>"}.
        text = tokenizer.apply_chat_template(
            ex["messages"], tokenize=False, add_generation_prompt=False
        )
        return {"text": text}

    dataset = dataset.map(format_example, remove_columns=dataset.column_names)
    print(f"  Sample row: {dataset[0]['text'][:300]}…")

    # 4. Configure trainer
    print("[4/6] Configuring trainer…")
    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        dataset_text_field="text",
        max_seq_length=MAX_SEQ_LENGTH,
        dataset_num_proc=2,
        packing=False,
        args=TrainingArguments(
            per_device_train_batch_size=BATCH_SIZE,
            gradient_accumulation_steps=GRADIENT_ACCUMULATION,
            warmup_steps=WARMUP_STEPS,
            num_train_epochs=NUM_EPOCHS,
            learning_rate=LEARNING_RATE,
            fp16=not torch.cuda.is_bf16_supported(),
            bf16=torch.cuda.is_bf16_supported(),
            logging_steps=10,
            optim="adamw_8bit",
            weight_decay=0.01,
            lr_scheduler_type="linear",
            seed=3407,
            output_dir=str(OUTPUT_DIR / "checkpoints"),
            save_strategy="no",
            report_to="none",
        ),
    )

    # 5. Train
    print("[5/6] Training…")
    trainer_stats = trainer.train()
    print(f"  Final loss: {trainer_stats.training_loss:.4f}")
    print(f"  Runtime:    {trainer_stats.metrics.get('train_runtime', 0):.1f}s")

    # 6. Save LoRA + merged + GGUF
    print("[6/6] Saving artefacts…")
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # LoRA adapter only (small, ~50 MB)
    model.save_pretrained(str(OUTPUT_DIR))
    tokenizer.save_pretrained(str(OUTPUT_DIR))
    print(f"  Saved LoRA adapter: {OUTPUT_DIR}")

    # Merged model (full base + LoRA, ~5 GB fp16)
    MERGED_DIR.mkdir(parents=True, exist_ok=True)
    model.save_pretrained_merged(str(MERGED_DIR), tokenizer, save_method="merged_16bit")
    print(f"  Saved merged model: {MERGED_DIR}")

    # GGUF for Ollama (handles quantisation back to 4-bit q4_k_m)
    gguf_dir = OUTPUT_DIR.with_name(OUTPUT_DIR.name + "-gguf")
    model.save_pretrained_gguf(str(gguf_dir), tokenizer, quantization_method="q4_k_m")
    print(f"  Saved GGUF (q4_k_m): {gguf_dir}")

    print()
    print("Done. Next steps:")
    print(f"  1. Smoke-test the GGUF with Ollama: ")
    print(f"       ollama create bounds-gemma-phi -f {gguf_dir}/Modelfile")
    print(f"       ollama run bounds-gemma-phi 'Patient presents with anxiety.'")
    print(f"  2. Export to LiteRT-LM .task for WebLLM (separate script):")
    print(f"       python finetune/scripts/export_litert.py")
    print(f"  3. Push to HuggingFace:")
    print(f"       huggingface-cli login")
    print(f"       huggingface-cli upload Aqta-ai/bounds-gemma-e2b-phi-ft {MERGED_DIR}")
    print(f"       huggingface-cli upload Aqta-ai/bounds-gemma-e2b-phi-ft-gguf {gguf_dir}")


if __name__ == "__main__":
    main()
